
name: Zotero to Readwise Automation

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "0 3 * * *" # Runs at 03:00 AM (UTC) every day (Check https://crontab.guru/)

jobs:
  zotero-to-readwise-automation:
    runs-on: ubuntu-latest
    steps:
      - name: 🍽️ Checkout the repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: 🐍 Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install
        run: pip3 install pyzotero

      - name: 🚀 Run Automation
        run: /bin/bash ./auto.sh ${{ secrets.READWISE_TOKEN }} ${{ secrets.ZOTERO_KEY }} ${{ secrets.ZOTERO_ID }}
      
      - name: Commit changes of version number
        uses: EndBug/add-and-commit@v9
        with:
          author_name: wwyf
          author_email: w.y.ff@163.com
          message: 'update version number'
          add: 'zotero_version_number'